In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils import data
import torchvision
import torchvision.models as models


import os
import numpy as np
import librosa
import os
import torch
import torchaudio.transforms as T
import datetime
from tqdm import tqdm
import torch.optim as optim
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader

#import own modules
import config
from utils_dir import transforms 

#empty cache
torch.cuda.empty_cache()


# CUDA for PyTorch
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

###############Dataloader for training the model####################
from DL_finetune import ESC_50_DL_finetune as DSf

In [2]:
class Resnet50_Classifier(nn.Module):
    def __init__(self, num_classes):
        super(Resnet50_Classifier, self).__init__()

        # Load the pretrained ResNet-50 model
        self.resnet50 = models.resnet50(pretrained=True)

        # Change the first layer to accept 1-channel input (instead of the default 3 channels for RGB)
        self.resnet50.conv1 = nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)
        
        # Modify the last fully connected layer to match the number of classes
        num_features = self.resnet50.fc.in_features
        self.resnet50.fc = nn.Linear(num_features, num_classes)

    def forward(self, x):
        return self.resnet50(x)

In [3]:

# Hyperparameters
num_epochs = 400
learning_rate = 0.001
weight_decay = 1e-5  # L2 regularization
batch_size = 32

# Device configuration
#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Early stopping parameters
patience = 60  # This value can be changed based on how many epochs of no improvement you're willing to wait
early_stop_counter = 0

# Initialize dataset and dataloaders
train_loader, test_loader = DSf.create_generators_finetune()

# Initialize the Classifier
num_classes = 50  
model = Resnet50_Classifier(num_classes=num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

# Create log directory
current_date = datetime.datetime.now().strftime('%Y-%m-%d-%H')
log_dir = f"./results_standalone/ResnetClassifier-{current_date}-epochs-{num_epochs}"
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

# Log file path
log_file_path = os.path.join(log_dir, "training_log.txt")

# Variables for checkpointing
best_val_loss = float('inf')

# Training loop
for epoch in range(num_epochs):
    model.train()
    train_loss = 0.0
    
    for _, (file_name, data, labels) in tqdm(enumerate(train_loader), total=len(train_loader)):
        data, labels = data.to(device), labels.to(device)

        # Forward pass
        outputs = model(data)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item()
        
    avg_train_loss = train_loss / len(train_loader)

    # Validation loop
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for _, (file_name, data, labels) in tqdm(enumerate(test_loader), total=len(test_loader)):
            data, labels = data.to(device), labels.to(device)
            outputs = model(data)
            loss = criterion(outputs, labels)
            val_loss += loss.item()
            
    avg_val_loss = val_loss / len(test_loader)

    # Check for early stopping
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        print("Validation Loss improved! Saving the model...")
        torch.save(model, log_dir + '/checkpoint.pth')
        early_stop_counter = 0
    else:
        early_stop_counter += 1
        if early_stop_counter >= patience:
            print("Early stopping!")
            break

    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}')
    
    # Log to file
    with open(log_file_path, 'a') as log_file:
        log_file.write(f"Epoch [{epoch+1}/{num_epochs}] Training Loss: {avg_train_loss:.4f}, Validation Loss: {avg_val_loss:.4f}\n")


c:\Users\Gabriel\anaconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\Gabriel\anaconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
100%|██████████| 13/13 [00:04<00:00,  2.62it/s]


Validation Loss improved! Saving the model...
Epoch [1/400], Train Loss: 3.7365, Val Loss: 4.1258


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Validation Loss improved! Saving the model...
Epoch [2/400], Train Loss: 3.1010, Val Loss: 3.2812


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Epoch [3/400], Train Loss: 2.8176, Val Loss: 3.7458


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Validation Loss improved! Saving the model...
Epoch [4/400], Train Loss: 2.5067, Val Loss: 2.4488


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Validation Loss improved! Saving the model...
Epoch [5/400], Train Loss: 2.2943, Val Loss: 2.3960


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Validation Loss improved! Saving the model...
Epoch [6/400], Train Loss: 2.0682, Val Loss: 2.3391


100%|██████████| 13/13 [00:04<00:00,  2.74it/s]


Epoch [7/400], Train Loss: 1.8672, Val Loss: 2.7581


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Validation Loss improved! Saving the model...
Epoch [8/400], Train Loss: 1.7441, Val Loss: 1.9852


100%|██████████| 13/13 [00:04<00:00,  2.66it/s]


Validation Loss improved! Saving the model...
Epoch [9/400], Train Loss: 1.5699, Val Loss: 1.7404


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Epoch [10/400], Train Loss: 1.4889, Val Loss: 7.9080


100%|██████████| 13/13 [00:04<00:00,  2.78it/s]


Epoch [11/400], Train Loss: 1.3988, Val Loss: 4.0100


100%|██████████| 13/13 [00:04<00:00,  2.81it/s]


Epoch [12/400], Train Loss: 1.2920, Val Loss: 1.9115


100%|██████████| 13/13 [00:04<00:00,  2.79it/s]


Epoch [13/400], Train Loss: 1.1934, Val Loss: 4.1438


100%|██████████| 13/13 [00:04<00:00,  2.81it/s]


Epoch [14/400], Train Loss: 1.1575, Val Loss: 2.7720


100%|██████████| 13/13 [00:04<00:00,  2.76it/s]


Epoch [15/400], Train Loss: 1.1079, Val Loss: 3.2186


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [16/400], Train Loss: 0.9951, Val Loss: 2.1603


100%|██████████| 13/13 [00:04<00:00,  2.78it/s]


Epoch [17/400], Train Loss: 1.0122, Val Loss: 2.7968


100%|██████████| 13/13 [00:04<00:00,  2.82it/s]


Epoch [18/400], Train Loss: 0.9190, Val Loss: 1.8662


100%|██████████| 13/13 [00:04<00:00,  2.79it/s]


Epoch [19/400], Train Loss: 0.8610, Val Loss: 1.8774


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [20/400], Train Loss: 0.8891, Val Loss: 2.4818


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [21/400], Train Loss: 0.7711, Val Loss: 1.9117


100%|██████████| 13/13 [00:04<00:00,  2.68it/s]


Validation Loss improved! Saving the model...
Epoch [22/400], Train Loss: 0.7282, Val Loss: 1.4022


100%|██████████| 13/13 [00:04<00:00,  2.72it/s]


Epoch [23/400], Train Loss: 0.7670, Val Loss: 2.6847


100%|██████████| 13/13 [00:04<00:00,  2.67it/s]


Epoch [24/400], Train Loss: 0.7170, Val Loss: 1.5150


100%|██████████| 13/13 [00:04<00:00,  2.70it/s]


Epoch [25/400], Train Loss: 0.6485, Val Loss: 3.0967


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [26/400], Train Loss: 0.6009, Val Loss: 3.1395


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [27/400], Train Loss: 0.6365, Val Loss: 1.8836


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [28/400], Train Loss: 0.5643, Val Loss: 4.7128


100%|██████████| 13/13 [00:04<00:00,  2.72it/s]


Epoch [29/400], Train Loss: 0.5832, Val Loss: 2.8293


100%|██████████| 13/13 [00:04<00:00,  2.80it/s]


Epoch [30/400], Train Loss: 0.5585, Val Loss: 1.9416


100%|██████████| 13/13 [00:04<00:00,  2.75it/s]


Epoch [31/400], Train Loss: 0.5610, Val Loss: 14.4098


100%|██████████| 13/13 [00:04<00:00,  2.70it/s]


Epoch [32/400], Train Loss: 0.4993, Val Loss: 3.1973


100%|██████████| 13/13 [00:04<00:00,  2.74it/s]


Epoch [33/400], Train Loss: 0.4882, Val Loss: 3.0552


100%|██████████| 13/13 [00:04<00:00,  2.72it/s]


Epoch [34/400], Train Loss: 0.4939, Val Loss: 1.6117


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [35/400], Train Loss: 0.5170, Val Loss: 1.6944


100%|██████████| 13/13 [00:04<00:00,  2.76it/s]


Validation Loss improved! Saving the model...
Epoch [36/400], Train Loss: 0.4183, Val Loss: 1.3260


100%|██████████| 13/13 [00:04<00:00,  2.80it/s]


Epoch [37/400], Train Loss: 0.4043, Val Loss: 3.6283


100%|██████████| 13/13 [00:04<00:00,  2.69it/s]


Validation Loss improved! Saving the model...
Epoch [38/400], Train Loss: 0.4572, Val Loss: 1.2484


100%|██████████| 13/13 [00:04<00:00,  2.67it/s]


Epoch [39/400], Train Loss: 0.3992, Val Loss: 1.3650


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Epoch [40/400], Train Loss: 0.3989, Val Loss: 2.1647


100%|██████████| 13/13 [00:08<00:00,  1.54it/s]


Epoch [41/400], Train Loss: 0.3459, Val Loss: 1.3499


100%|██████████| 13/13 [00:08<00:00,  1.58it/s]


Epoch [42/400], Train Loss: 0.4066, Val Loss: 1.4222


100%|██████████| 13/13 [00:08<00:00,  1.57it/s]


Epoch [43/400], Train Loss: 0.4216, Val Loss: 2.5902


100%|██████████| 13/13 [00:08<00:00,  1.54it/s]


Epoch [44/400], Train Loss: 0.3656, Val Loss: 1.4589


100%|██████████| 13/13 [00:08<00:00,  1.60it/s]


Epoch [45/400], Train Loss: 0.3812, Val Loss: 6.0230


100%|██████████| 13/13 [00:08<00:00,  1.61it/s]


Epoch [46/400], Train Loss: 0.3682, Val Loss: 2.5887


100%|██████████| 13/13 [00:08<00:00,  1.60it/s]


Epoch [47/400], Train Loss: 0.3628, Val Loss: 2.2940


100%|██████████| 13/13 [00:07<00:00,  1.63it/s]


Epoch [48/400], Train Loss: 0.3267, Val Loss: 3.9221


100%|██████████| 13/13 [00:08<00:00,  1.61it/s]


Epoch [49/400], Train Loss: 0.3067, Val Loss: 2.1591


100%|██████████| 13/13 [00:08<00:00,  1.62it/s]


Epoch [50/400], Train Loss: 0.2936, Val Loss: 1.8927


100%|██████████| 13/13 [00:08<00:00,  1.61it/s]


Validation Loss improved! Saving the model...
Epoch [51/400], Train Loss: 0.3021, Val Loss: 1.1345


100%|██████████| 13/13 [00:08<00:00,  1.62it/s]


Epoch [52/400], Train Loss: 0.2770, Val Loss: 1.5259


100%|██████████| 13/13 [00:04<00:00,  2.75it/s]


Epoch [53/400], Train Loss: 0.3210, Val Loss: 3.8112


100%|██████████| 13/13 [00:04<00:00,  2.69it/s]


Epoch [54/400], Train Loss: 0.3448, Val Loss: 1.5770


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [55/400], Train Loss: 0.3346, Val Loss: 4.1949


100%|██████████| 13/13 [00:04<00:00,  2.72it/s]


Epoch [56/400], Train Loss: 0.2101, Val Loss: 1.7397


100%|██████████| 13/13 [00:04<00:00,  2.70it/s]


Epoch [57/400], Train Loss: 0.2596, Val Loss: 4.3703


100%|██████████| 13/13 [00:04<00:00,  2.71it/s]


Epoch [58/400], Train Loss: 0.2849, Val Loss: 2.0516


100%|██████████| 13/13 [00:04<00:00,  2.65it/s]


Epoch [59/400], Train Loss: 0.2685, Val Loss: 1.6696


100%|██████████| 13/13 [00:04<00:00,  2.65it/s]


Epoch [60/400], Train Loss: 0.2650, Val Loss: 3.4501


100%|██████████| 13/13 [00:04<00:00,  2.64it/s]


Epoch [61/400], Train Loss: 0.2533, Val Loss: 1.2177


100%|██████████| 13/13 [00:04<00:00,  2.67it/s]


Epoch [62/400], Train Loss: 0.2977, Val Loss: 2.7006


100%|██████████| 13/13 [00:04<00:00,  2.67it/s]


Epoch [63/400], Train Loss: 0.3255, Val Loss: 4.2954


100%|██████████| 13/13 [00:04<00:00,  2.73it/s]


Epoch [64/400], Train Loss: 0.2899, Val Loss: 2.0937


100%|██████████| 13/13 [00:04<00:00,  2.72it/s]


Epoch [65/400], Train Loss: 0.2741, Val Loss: 2.7389


100%|██████████| 13/13 [00:06<00:00,  1.99it/s]


Epoch [66/400], Train Loss: 0.2522, Val Loss: 1.5666


100%|██████████| 13/13 [00:08<00:00,  1.53it/s]


Epoch [67/400], Train Loss: 0.2593, Val Loss: 4.6022


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Validation Loss improved! Saving the model...
Epoch [68/400], Train Loss: 0.1873, Val Loss: 1.0771


100%|██████████| 13/13 [00:09<00:00,  1.42it/s]


Epoch [69/400], Train Loss: 0.1728, Val Loss: 1.9008


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [70/400], Train Loss: 0.2531, Val Loss: 4.0970


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [71/400], Train Loss: 0.2312, Val Loss: 4.8183


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [72/400], Train Loss: 0.2386, Val Loss: 1.3322


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [73/400], Train Loss: 0.2369, Val Loss: 1.3744


100%|██████████| 13/13 [00:09<00:00,  1.43it/s]


Epoch [74/400], Train Loss: 0.2410, Val Loss: 1.3978


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [75/400], Train Loss: 0.1557, Val Loss: 1.6368


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [76/400], Train Loss: 0.1535, Val Loss: 1.9693


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [77/400], Train Loss: 0.2306, Val Loss: 1.3504


100%|██████████| 13/13 [00:08<00:00,  1.53it/s]


Epoch [78/400], Train Loss: 0.2117, Val Loss: 2.8239


100%|██████████| 13/13 [00:05<00:00,  2.55it/s]


Epoch [79/400], Train Loss: 0.1911, Val Loss: 1.4353


100%|██████████| 13/13 [00:08<00:00,  1.53it/s]


Epoch [80/400], Train Loss: 0.1889, Val Loss: 3.3203


100%|██████████| 13/13 [00:08<00:00,  1.61it/s]


Epoch [81/400], Train Loss: 0.2311, Val Loss: 1.6473


100%|██████████| 13/13 [00:08<00:00,  1.62it/s]


Epoch [82/400], Train Loss: 0.2111, Val Loss: 1.3170


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [83/400], Train Loss: 0.1876, Val Loss: 1.4676


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [84/400], Train Loss: 0.1865, Val Loss: 1.2494


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [85/400], Train Loss: 0.1771, Val Loss: 2.2270


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [86/400], Train Loss: 0.1668, Val Loss: 1.3332


100%|██████████| 13/13 [00:08<00:00,  1.53it/s]


Epoch [87/400], Train Loss: 0.1658, Val Loss: 2.2431


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [88/400], Train Loss: 0.1936, Val Loss: 3.9585


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [89/400], Train Loss: 0.1652, Val Loss: 1.6741


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [90/400], Train Loss: 0.2191, Val Loss: 2.1837


100%|██████████| 13/13 [00:08<00:00,  1.48it/s]


Epoch [91/400], Train Loss: 0.2138, Val Loss: 1.6791


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [92/400], Train Loss: 0.1913, Val Loss: 1.7123


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [93/400], Train Loss: 0.1551, Val Loss: 3.1859


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [94/400], Train Loss: 0.1082, Val Loss: 1.2446


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [95/400], Train Loss: 0.1692, Val Loss: 1.3093


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [96/400], Train Loss: 0.1921, Val Loss: 1.4469


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [97/400], Train Loss: 0.1997, Val Loss: 4.0508


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [98/400], Train Loss: 0.1370, Val Loss: 1.2180


100%|██████████| 13/13 [00:08<00:00,  1.55it/s]


Epoch [99/400], Train Loss: 0.1130, Val Loss: 1.3824


100%|██████████| 13/13 [00:08<00:00,  1.59it/s]


Epoch [100/400], Train Loss: 0.1436, Val Loss: 1.6245


100%|██████████| 13/13 [00:07<00:00,  1.63it/s]


Epoch [101/400], Train Loss: 0.1429, Val Loss: 1.4002


100%|██████████| 13/13 [00:08<00:00,  1.54it/s]


Epoch [102/400], Train Loss: 0.1284, Val Loss: 1.8044


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [103/400], Train Loss: 0.2258, Val Loss: 3.9370


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [104/400], Train Loss: 0.1521, Val Loss: 1.3775


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [105/400], Train Loss: 0.1529, Val Loss: 1.8525


100%|██████████| 13/13 [00:08<00:00,  1.53it/s]


Epoch [106/400], Train Loss: 0.1419, Val Loss: 1.3604


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [107/400], Train Loss: 0.1922, Val Loss: 9.1923


100%|██████████| 13/13 [00:08<00:00,  1.49it/s]


Epoch [108/400], Train Loss: 0.1308, Val Loss: 3.0020


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [109/400], Train Loss: 0.1264, Val Loss: 2.4691


100%|██████████| 13/13 [00:08<00:00,  1.62it/s]


Epoch [110/400], Train Loss: 0.1410, Val Loss: 1.2785


100%|██████████| 13/13 [00:08<00:00,  1.60it/s]


Epoch [111/400], Train Loss: 0.1393, Val Loss: 1.9066


100%|██████████| 13/13 [00:08<00:00,  1.61it/s]


Epoch [112/400], Train Loss: 0.1634, Val Loss: 1.3726


100%|██████████| 13/13 [00:08<00:00,  1.60it/s]


Epoch [113/400], Train Loss: 0.1496, Val Loss: 1.6060


100%|██████████| 13/13 [00:08<00:00,  1.53it/s]


Epoch [114/400], Train Loss: 0.1543, Val Loss: 1.2488


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [115/400], Train Loss: 0.1212, Val Loss: 7.5496


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [116/400], Train Loss: 0.1298, Val Loss: 1.5045


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [117/400], Train Loss: 0.1393, Val Loss: 7.7099


100%|██████████| 13/13 [00:08<00:00,  1.50it/s]


Epoch [118/400], Train Loss: 0.1297, Val Loss: 1.5852


100%|██████████| 13/13 [00:08<00:00,  1.51it/s]


Epoch [119/400], Train Loss: 0.1247, Val Loss: 2.5285


100%|██████████| 13/13 [00:08<00:00,  1.46it/s]


Epoch [120/400], Train Loss: 0.1662, Val Loss: 4.3850


100%|██████████| 13/13 [00:08<00:00,  1.60it/s]


Epoch [121/400], Train Loss: 0.1270, Val Loss: 1.3290


100%|██████████| 13/13 [00:08<00:00,  1.58it/s]


Epoch [122/400], Train Loss: 0.1352, Val Loss: 2.5799


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [123/400], Train Loss: 0.1253, Val Loss: 4.2123


100%|██████████| 13/13 [00:08<00:00,  1.52it/s]


Epoch [124/400], Train Loss: 0.1056, Val Loss: 1.4053


100%|██████████| 13/13 [00:08<00:00,  1.61it/s]


Epoch [125/400], Train Loss: 0.1395, Val Loss: 2.0440


100%|██████████| 13/13 [00:08<00:00,  1.58it/s]


Epoch [126/400], Train Loss: 0.1766, Val Loss: 2.3947


100%|██████████| 13/13 [00:08<00:00,  1.59it/s]


Epoch [127/400], Train Loss: 0.1303, Val Loss: 2.5331


100%|██████████| 13/13 [00:08<00:00,  1.60it/s]

Early stopping!


In [4]:
# Import necessary libraries
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support

def evaluate_model_standalone(test_loader, model):
    model.eval()
    true_labels = []
    pred_labels = []
    
    with torch.no_grad():
        for (file_name, data, labels) in tqdm(test_loader):
            data, labels = data.to(device), labels.to(device)
            
            outputs = model(data)
            
            true_labels.extend(labels.cpu().numpy())
            pred_labels.extend(torch.argmax(outputs, dim=1).cpu().numpy())
            
    # Calculate accuracy
    correct_preds = sum(t == p for t, p in zip(true_labels, pred_labels))
    accuracy = correct_preds / len(true_labels)

    # Calculate precision, recall, F1-score
    precision, recall, f1_score, support = precision_recall_fscore_support(true_labels, pred_labels, average='weighted')

    # Calculate the confusion matrix
    conf_mat = confusion_matrix(true_labels, pred_labels)

    # Print the results
    print(f"\nEvaluation Results:")
    print(f"Accuracy: {accuracy * 100:.2f}%")
    print(f"Precision: {precision * 100:.2f}%")
    print(f"Recall: {recall * 100:.2f}%")
    print(f"F1-score: {f1_score * 100:.2f}%")
    print("Confusion Matrix:")
    print(conf_mat)

# Call the evaluate function after training
evaluate_model_standalone(test_loader, model)


  0%|          | 0/13 [00:00<?, ?it/s]

100%|██████████| 13/13 [00:08<00:00,  1.60it/s]


Evaluation Results:
Accuracy: 70.25%
Precision: 74.47%
Recall: 70.25%
F1-score: 68.45%
Confusion Matrix:
[[3 0 0 ... 0 0 0]
 [0 7 0 ... 0 0 0]
 [0 0 8 ... 0 0 0]
 ...
 [0 0 0 ... 6 0 0]
 [0 0 0 ... 0 7 0]
 [0 0 0 ... 0 0 5]]



c:\Users\Gabriel\anaconda3\envs\pytorch\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
